#!/usr/bin/env python
# -*- mode: python; -*-
'''

'''

DATE = "Sunday, May 13 2012"
AUTHOR = "Yagnesh Raghava Yakkala"
WEBSITE = "http://yagnesh.org"
LICENSE ="GPL v3 or later"

import os
import sys
import inspect

RUNWRFDIR = os.path.abspath(os.path.split(inspect.getfile(
    inspect.currentframe()))[0])

if RUNWRFDIR not in sys.path:
    sys.path.insert(0, RUNWRFDIR)

def main():
    pass

if __name__ == '__main__':
    main()
