#!/usr/bin/env python
# -*- mode: python; -*-
'''

'''

import os
import sys
import inspect

RUNWRFDIR = os.path.abspath(os.path.split(inspect.getfile(
    inspect.currentframe()))[0])

if RUNWRFDIR not in sys.path:
    sys.path.insert(0, RUNWRFDIR)

def main():
    pass

if __name__ == '__main__':
    main()
